import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image"
import Link from "next/link";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tanugoSans = localFont({
  src: "../public/fonts/Tanugo-TTF-Regular.ttf",
  variable: "--font-sans",
  display: "swap",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "鄧柏希個人名片",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en"
      className={`${tanugoSans.variable} ${geistMono.variable} h-full antialiased`}
    >

            
      <body className="min-h-full flex flex-col">
        

      <div className="flex h-full ">

    <main className="flex min-h-full w-full gap-6 overflow-hidden bg-[url('/background.jpg')] bg-cover p-10 pb-20">
      

        {/* 左邊 */}
      

        <div
          className="h-[90%] rounded-2xl bg-[url('/background_about.jpg')] bg-cover bg-center bg-no-repeat bg-fixed p-4 shadow-lg shadow-slate-900/10 transition-[box-shadow,transform] duration-300 ease-out hover:shadow-xl hover:shadow-slate-900/15 motion-reduce:transition-none motion-reduce:hover:shadow-lg"
        >

          <div className="m-auto flex h-[80px] w-[80px] items-center justify-center overflow-hidden rounded-full bg-gray-200 shadow-md ring-2 ring-white/50 transition-all duration-300 ease-out hover:scale-105 hover:shadow-lg hover:ring-white/80 motion-reduce:hover:scale-100">
            <Image src="/icons/me.jpg" alt="me" width={80} height={80} />
          </div>

           <div className="text-center">
              <p className=" text-slate-700">鄧柏希</p>
           </div>

           <div className="text-center">
              <p className="Tanugo-font text-slate-700">心理學,科技,影音領域反複橫跳的人類</p>
           </div>

          <div className="m-auto flex max-w-[200px] justify-center gap-2">
            <Link
              href="https://www.linkedin.com/in/cube-mo-227096393"
              target="_blank"
              rel="noopener noreferrer"
              className="flex h-[50px] w-[50px] items-center justify-center overflow-hidden rounded-2xl bg-white/90 shadow-sm ring-1 ring-slate-200/80 transition-all duration-200 ease-out hover:scale-110 hover:shadow-md hover:ring-blue-200 active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2 motion-reduce:hover:scale-100"
            >
              <Image src="/icons/linkedin.png" alt="LinkedIn" width={80} height={80} />
            </Link>

            <Link
              href="https://www.instagram.com/cube_mo?igsh=djFjY2p6NHkwcDV2&utm_source=qr"
              target="_blank"
              rel="noopener noreferrer"
              className="flex h-[50px] w-[50px] items-center justify-center overflow-hidden rounded-2xl bg-white/90 shadow-sm ring-1 ring-slate-200/80 transition-all duration-200 ease-out hover:scale-110 hover:shadow-md hover:ring-pink-200 active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-500 focus-visible:ring-offset-2 motion-reduce:hover:scale-100"
            >
              <Image src="/icons/instagram.jpg" alt="Instagram" width={80} height={80} />
            </Link>

            <Link
              href="https://www.facebook.com/share/1Dhaktvpjw/?mibextid=LQQJ4d"
              target="_blank"
              rel="noopener noreferrer"
              className="flex h-[50px] w-[50px] items-center justify-center overflow-hidden rounded-2xl bg-white/90 shadow-sm ring-1 ring-slate-200/80 transition-all duration-200 ease-out hover:scale-110 hover:shadow-md hover:ring-blue-300 active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 motion-reduce:hover:scale-100"
            >
              <Image src="/icons/facebook.webp" alt="Facebook" width={80} height={80} />
            </Link>
          </div>

        

          <nav className="mt-3 flex flex-col gap-2" aria-label="主要導覽">
            <Link
              href="/about"
              className="block rounded-lg bg-blue-200 px-4 py-3 text-center text-slate-800 shadow-sm transition-all duration-200 ease-out hover:translate-x-1 hover:bg-blue-300 hover:shadow-md active:scale-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-700 focus-visible:ring-offset-2 motion-reduce:hover:translate-x-0"
            >
              關於我
            </Link>
            <Link
              href="/hobby"
              className="block rounded-lg bg-blue-200 px-4 py-3 text-center text-slate-800 shadow-sm transition-all duration-200 ease-out hover:translate-x-1 hover:bg-blue-300 hover:shadow-md active:scale-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-700 focus-visible:ring-offset-2 motion-reduce:hover:translate-x-0"
            >
              我的興趣
            </Link>
            <Link
              href="/portfolio"
              className="block rounded-lg bg-blue-200 px-4 py-3 text-center text-slate-800 shadow-sm transition-all duration-200 ease-out hover:translate-x-1 hover:bg-blue-300 hover:shadow-md active:scale-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-700 focus-visible:ring-offset-2 motion-reduce:hover:translate-x-0"
            >
              作品集
            </Link>
            <Link
              href="/project"
              className="block rounded-lg bg-blue-200 px-4 py-3 text-center text-slate-800 shadow-sm transition-all duration-200 ease-out hover:translate-x-1 hover:bg-blue-300 hover:shadow-md active:scale-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-700 focus-visible:ring-offset-2 motion-reduce:hover:translate-x-0"
            >
              課程專案
            </Link>
          </nav>

        </div>


        <Link
          href="/"
          className="fixed bottom-10 right-10 z-50 rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2"
          aria-label="回到首頁"
        >
          <span className="flex cursor-pointer items-center gap-1 rounded-full border border-gray-200 bg-white px-4 py-3 text-sm text-blue-900 shadow-lg transition-all duration-200 ease-out hover:scale-110 hover:shadow-xl hover:shadow-slate-900/15 active:scale-95 motion-reduce:hover:scale-100">
            <span className="font-bold">🏠</span>
            <span className="font-medium">首頁</span>
          </span>
        </Link>

        <div className="bg-transparent w-full rounded-2xl h-screen">

           {children}

        </div>

      </main>
       </div>


      
        




      </body>
    </html>
  );
}
