import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image"
import Link from "next/link";

import { TbActivity } from "react-icons/tb";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "鄧柏希個人履歷表",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        

      <div className="flex h-full">




        {/* 左邊 */}

        <div className="bg-[url('/background.jpg')] h-screen p-4">

       

          <div className="bg-gray-200 w-[80px] h-[80px] rounded-full overflow-hidden flex justify-center items-center m-auto">
            <Image src="/icons/me.jpg" alt="me" width={80} height={80}/>  



          </div>
          <div className="text-center">
          <p className="custom-text text-slate-700">鄧柏希</p>
          </div>
          <div className="text-center">
           <p className="custom-text text-slate-700">心理學,科技,影音領域反複橫跳的人類</p>
          </div>

          <div className="flex gap-2">
            {/* icons, links, images */}


             {/*  lindedin圖案連結  */}
            <div className="bg-white-100 w-[50px] h-[50px]  rounded-2xl overflow-hidden flex justify-center items-center m-auto">
             <Link href="www.linkedin.com/in/cube-mo-227096393" target="_blank">
               <Image src="/icons/linkedin.png" alt="linkedin" width={80} height={80}/>
              </Link>
            </div>

            {/*  ig圖案連結  */}
            <div className="bg-white-100 w-[50px] h-[50px]  rounded-2xl overflow-hidden flex justify-center items-center m-auto">
             <Link href="https://www.instagram.com/cube_mo?igsh=djFjY2p6NHkwcDV2&utm_source=qr" target="_blank">
               <Image src="/icons/instagram.jpg" alt="instagram" width={80} height={80}/>
              </Link>
            </div>

            {/*  fb圖案連結  */}
            <div className="bg-white-100 w-[50px] h-[50px] rounded-2x1 overflow-hidden flex justify-center items-center m-auto">
             <Link href="https://www.facebook.com/share/1Dhaktvpjw/?mibextid=LQQJ4d" target="_blank">
               <Image src="/icons/facebook.webp" alt="facebook" width={80} height={80}/>
             </Link>
            </div>

          </div>

        

          
          <Link href="/about">
            <div className="bg-blue-300 p-[16px] mt-2 rounded-md">關於我 </div>
          </Link>

          <Link href="/hobby">
            <div className="bg-blue-300 p-[16px] mt-2 rounded-md">我的興趣 </div>
          </Link>
          
          <div className="bg-blue-300 p-[16px] mt-2 rounded-md">設計專案 </div>
          <div className="bg-blue-300 p-[16px] mt-2 rounded-md">程式專案 </div>

        </div>
        <div className="bg-gray-200 w-full h-screen">

           {children}

        </div>


       </div>


      
        




      </body>
    </html>
  );
}
