import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image"
import Link from "next/link";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tanugoSans = localFont({
  src: "../public/fonts/Tanugo-TTF-Regular.ttf",
  variable: "--font-sans",
  display: "swap",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "鄧柏希個人名片",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en"
      className={`${tanugoSans.variable} ${geistMono.variable} h-full antialiased`}
    >

            
      <body className="min-h-full flex flex-col">
        

      <div className="flex h-full ">

    <main className="flex min-h-screen w-full pb-20w-full 
    overflow-hidden bg-[url('/background.jpg')] 
     bg-cover  p-10  gap-6">
      

        {/* 左邊 */}
      

        <div className="
        
        h-[90%]
        bg-[url('/background_about.jpg')] 
        bg-cover bg-center bg-no-repeat
        bg-fixed
        rounded-2xl
        p-4">

       

          <div className="bg-gray-200 w-[80px] h-[80px] rounded-full overflow-hidden flex justify-center items-center m-auto">
            <Image src="/icons/me.jpg" alt="me" width={80} height={80}/>  



          </div>

           <div className="text-center">
              <p className=" text-slate-700">鄧柏希</p>
           </div>

           <div className="text-center">
              <p className="Tanugo-font text-slate-700">心理學,科技,影音領域反複橫跳的人類</p>
           </div>

          <div className="flex gap-2">
            {/* icons, links, images */}


             {/*  lindedin圖案連結  */}
            <div className="bg-white-100 w-[50px] h-[50px]  rounded-2xl overflow-hidden flex justify-center items-center m-auto">
             <Link href="https://www.linkedin.com/in/cube-mo-227096393" target="_blank">
              
                  
                 <Image src="/icons/linkedin.png" alt="linkedin" width={80} height={80}/>
               
              </Link>
            </div>

            {/*  ig圖案連結  */}
            <div className="bg-white-100 w-[50px] h-[50px]  rounded-2xl overflow-hidden flex justify-center items-center m-auto">
             <Link href="https://www.instagram.com/cube_mo?igsh=djFjY2p6NHkwcDV2&utm_source=qr" target="_blank">
               <Image src="/icons/instagram.jpg" alt="instagram" width={80} height={80}/>
              </Link>
            </div>

            {/*  fb圖案連結  */}
            <div className="bg-white-100 w-[50px] h-[50px] rounded-2x1 overflow-hidden flex justify-center items-center m-auto">
             <Link href="https://www.facebook.com/share/1Dhaktvpjw/?mibextid=LQQJ4d" target="_blank">
               <Image src="/icons/facebook.webp" alt="facebook" width={80} height={80}/>
             </Link>
            </div>

          </div>

        

          
          <Link href="/about">
            <div className="bg-blue-200 p-[16px] mt-2 rounded-md">關於我 </div>
          </Link>

          <Link href="/hobby">
            <div className="bg-blue-200 p-[16px] mt-2 rounded-md">我的興趣 </div>
          </Link>
          <Link href="/portfolio">
            <div className="bg-blue-200 p-[16px] mt-2 rounded-md">作品集 </div>
          </Link>
          <Link href="/project">
           <div className="bg-blue-200 p-[16px] mt-2 rounded-md">課程專案 </div>
          </Link>

        </div>


        <Link href="/" className="fixed bottom-10 right-10 z-50">
          <div className="bg-white p-4 rounded-full shadow-lg border border-gray-200 hover:scale-110 transition-transform cursor-pointer">
            home{/* 這裡可以放一個家的圖示，或簡單寫個 Home */}
            <span className="text-blue-900 font-bold">🏠</span>
          </div>
        </Link>

        <div className="bg-transparent w-full rounded-2xl h-screen">

           {children}

        </div>

      </main>
       </div>


      
        




      </body>
    </html>
  );
}
